import assert from 'node:assert/strict';
import {createServer} from 'node:http';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';import {chromium} from 'playwright';
const root=resolve('.'),out=resolve(process.env.MAGE_REVIEW_OUT||'.local/mage');await mkdir(out,{recursive:true});
const html=`<!doctype html><style>body{margin:0;background:#b5b2a6}canvas{display:block}</style><script type="importmap">{"imports":{"three":"/node_modules/three/build/three.module.js","three/":"/node_modules/three/"}}</script><script type="module">
import * as T from 'three';import {loadCharacters,makeCharacter} from '/src/three/characters.js';
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1100,1100);renderer.setPixelRatio(1);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;document.body.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#aaa99e');scene.add(new T.HemisphereLight(0xe1eaff,0x8b7764,2));const sun=new T.DirectionalLight(0xffe9ce,3);sun.position.set(3,5,4);scene.add(sun);const rim=new T.DirectionalLight(0xffffff,1.5);rim.position.set(-3,3,-3);scene.add(rim);
const camera=new T.PerspectiveCamera(30,1,.01,30);const ground=new T.Mesh(new T.PlaneGeometry(20,20),new T.MeshStandardMaterial({color:'#aaa99e',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.01;scene.add(ground);
await loadCharacters();const char=makeCharacter('Celestial Mage',1.818);scene.add(char.root);char.play('Idle_A',{fade:0});char.update(.2);const frame=(angle=0,close=false)=>{camera.position.set(Math.sin(angle)*(close?1.35:4.8),close?1.77:1.4,Math.cos(angle)*(close?1.35:4.8));camera.lookAt(0,close?1.72:1.12,0);scene.updateMatrixWorld(true);renderer.render(scene,camera);};frame();window.review={char,scene,camera,renderer,frame,T,makeCharacter};
</script>`;
const server=createServer(async(req,res)=>{try{if(process.env.MAGE_TEXTURE_FAIL&&req.url.startsWith('/assets/celestial-mage/')){res.writeHead(404).end();return;}if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const f=resolve(root,(req.url.startsWith('/assets/')?'./public':'.')+req.url.split('?')[0]);if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.js':'text/javascript','.glb':'model/gltf-binary'})[extname(f)]||'application/octet-stream');res.end(await readFile(f));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch(process.platform==='darwin'?{channel:'chromium'}:{args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:1100,height:1100}});page.on('pageerror',e=>console.error(e));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.review,null,{timeout:60000});assert.equal(await page.evaluate(()=>review.char.root.userData.celestialMage.textiles),!process.env.MAGE_TEXTURE_FAIL);for(const [name,angle,close]of [['front',0,false],['side',Math.PI/2,false],['back',Math.PI,false],['face',.2,true]]){await page.evaluate(([a,c])=>review.frame(a,c),[angle,close]);await page.screenshot({path:out+'/'+name+'.png'});}const report=await page.evaluate(()=>{const {char,T}=review;const report={};for(const name of ['Idle_A','Walking_A','Running_A','Jump_Idle','Interact']){if(!char.play(name,{fade:0})){report[name]='unavailable';continue;}const bounds=new T.Box3();let floor=Infinity;for(let i=0;i<30;i++){char.update(1/30);char.root.updateMatrixWorld(true);char.root.traverse(o=>{if(o.isSkinnedMesh){o.skeleton.update();const p=o.geometry.attributes.position;for(let j=0;j<p.count;j+=3){const v=new T.Vector3().fromBufferAttribute(p,j);o.applyBoneTransform(j,v);v.applyMatrix4(o.matrixWorld);bounds.expandByPoint(v);floor=Math.min(floor,v.y);}}});}report[name]={min:bounds.min.toArray(),max:bounds.max.toArray(),floor};}return report;});for(const [name,bounds] of Object.entries(report)){assert.notEqual(bounds,'unavailable',name);assert.ok([...bounds.min,...bounds.max].every(Number.isFinite),name+' finite skinning');assert.ok(bounds.floor>-.065,name+' sole penetration');assert.ok(bounds.max[1]<2.6,name+' stable retarget');}
const sharing=await page.evaluate(()=>{const {char,makeCharacter}=review;const before=char.bone('head').quaternion.toArray();const other=makeCharacter('Wizard',1.818);other.play('Walking_A',{fade:0});other.update(.7);const a=char.root.getObjectByName('Celestial_blue'),b=other.root.getObjectByName('Celestial_blue');let maxWeightError=0;char.root.traverse(o=>{if(!o.isSkinnedMesh)return;const w=o.geometry.attributes.skinWeight;for(let i=0;i<w.count;i++)maxWeightError=Math.max(maxWeightError,Math.abs(w.getX(i)+w.getY(i)+w.getZ(i)+w.getW(i)-1));});const result={independent:JSON.stringify(before)===JSON.stringify(char.bone('head').quaternion.toArray())&&a.skeleton!==b.skeleton,sharedGeometry:a.geometry===b.geometry,maxWeightError};other.dispose();review.frame();return result;});assert.equal(sharing.independent,true);assert.equal(sharing.sharedGeometry,true);assert.ok(sharing.maxWeightError<1e-6);report.instances=sharing;
const motion=await page.evaluate(()=>{const c=review.char;c.play('Idle_A',{fade:0});c.update(.1);const arm=c.bone('upperarml'),before=arm.quaternion.clone();for(let i=0;i<50;i++)c.update(0);const zeroDrift=arm.quaternion.angleTo(before);const drape=c.bone('drapel');let peak=0;for(let i=0;i<120;i++){c.root.rotation.y+=i<30?.04:0;c.update(1/60);peak=Math.max(peak,Math.abs(drape.rotation.z));}const result={zeroDrift,peak,settled:Math.abs(drape.rotation.z)};c.root.rotation.y=0;return result;});assert.ok(motion.zeroDrift<1e-6,'static animation does not accumulate pose offsets');assert.ok(motion.peak>.01&&motion.peak<.12,'turn response is present and bounded');assert.ok(motion.settled<.012,'cloth settles after the turn');report.motion=motion;
console.log(JSON.stringify(report,null,2));await writeFile(out+'/report.json',JSON.stringify(report,null,2));await page.evaluate(()=>{review.char.play('Walking_A',{fade:0});review.char.update(.25);review.frame(.3,false);});await page.screenshot({path:out+'/walking.png'});}finally{await browser.close();server.close();}
